"""schema initial

Revision ID: 0001
Revises:
Create Date: 2026-09-17 00:20:44.237704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('statut', sa.Enum('ACTIF', 'INACTIF', name='statut_actif_inactif', native_enum=False, length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('fournisseurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('pays', sa.String(length=100), nullable=True),
    sa.Column('observations', sa.String(length=500), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'INACTIF', name='statut_actif_inactif', native_enum=False, length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=150), nullable=False),
    sa.Column('produit', sa.String(length=100), nullable=False),
    sa.Column('edition', sa.Enum('DEMO', 'STANDARD', 'PROFESSIONAL', 'ENTREPRISE', name='edition_licence', native_enum=False, length=20), nullable=False),
    sa.Column('date_emission', sa.Date(), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_postes', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('ACTIVE', 'EXPIREE', 'INVALIDE', 'REVOQUEE', name='statut_licence', native_enum=False, length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motifs_sortie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('statut', sa.Enum('ACTIF', 'INACTIF', name='statut_actif_inactif', native_enum=False, length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('parametres',
    sa.Column('cle', sa.String(length=100), nullable=False),
    sa.Column('valeur', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cle')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unite', sa.String(length=20), nullable=False),
    sa.Column('fournisseur_principal_id', sa.Integer(), nullable=True),
    sa.Column('prix_achat_defaut', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prix_vente', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cout_moyen_pondere', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_actuel', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_min', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_max', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('emplacement', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('statut', sa.Enum('ACTIF', 'INACTIF', name='statut_actif_inactif', native_enum=False, length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.CheckConstraint('cout_moyen_pondere >= 0', name='ck_article_cmup_positif'),
    sa.CheckConstraint('prix_achat_defaut >= 0', name='ck_article_prix_achat_positif'),
    sa.CheckConstraint('prix_vente >= 0', name='ck_article_prix_vente_positif'),
    sa.CheckConstraint('stock_actuel >= 0', name='ck_article_stock_actuel_positif'),
    sa.CheckConstraint('stock_min >= 0', name='ck_article_stock_min_positif'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['fournisseur_principal_id'], ['fournisseurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_reference'), ['reference'], unique=True)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('dernier_login', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entite', sa.String(length=100), nullable=False),
    sa.Column('entite_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('resultat', sa.Enum('SUCCES', 'ECHEC', name='resultat_audit', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_date_heure'), ['date_heure'], unique=False)

    op.create_table('entrees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fournisseur_id', sa.Integer(), nullable=False),
    sa.Column('reference_document', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.Column('statut', sa.Enum('BROUILLON', 'VALIDEE', 'ANNULEE', name='statut_operation', native_enum=False, length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fournisseur_id'], ['fournisseurs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entrees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entrees_numero'), ['numero'], unique=True)

    op.create_table('inventaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('BROUILLON', 'VALIDE', name='statut_inventaire', native_enum=False, length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sorties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('motif_id', sa.Integer(), nullable=False),
    sa.Column('beneficiaire', sa.String(length=150), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.Column('statut', sa.Enum('BROUILLON', 'VALIDEE', 'ANNULEE', name='statut_operation', native_enum=False, length=20), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['motif_id'], ['motifs_sortie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sorties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sorties_numero'), ['numero'], unique=True)

    op.create_table('ventes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.Enum('BROUILLON', 'VALIDEE', 'ANNULEE', name='statut_operation', native_enum=False, length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ventes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ventes_numero'), ['numero'], unique=True)

    op.create_table('entree_lignes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entree_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('prix_unitaire >= 0', name='ck_entree_ligne_prix_positif'),
    sa.CheckConstraint('quantite > 0', name='ck_entree_ligne_quantite_positive'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['entree_id'], ['entrees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventaire_lignes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventaire_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('stock_theorique', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_physique', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('ecart', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['inventaire_id'], ['inventaires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sortie_lignes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sortie_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('cout_unitaire', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('cout_unitaire >= 0', name='ck_sortie_ligne_cout_positif'),
    sa.CheckConstraint('quantite > 0', name='ck_sortie_ligne_quantite_positive'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['sortie_id'], ['sorties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vente_lignes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vente_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sous_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('prix_unitaire >= 0', name='ck_vente_ligne_prix_positif'),
    sa.CheckConstraint('quantite > 0', name='ck_vente_ligne_quantite_positive'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['vente_id'], ['ventes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouvements_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_heure', sa.DateTime(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ENTREE', 'SORTIE', 'VENTE', 'AJUSTEMENT', 'ANNULATION', name='type_mouvement', native_enum=False, length=20), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_avant', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_apres', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('cout_unitaire', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('entree_ligne_id', sa.Integer(), nullable=True),
    sa.Column('sortie_ligne_id', sa.Integer(), nullable=True),
    sa.Column('vente_ligne_id', sa.Integer(), nullable=True),
    sa.Column('inventaire_ligne_id', sa.Integer(), nullable=True),
    sa.Column('mouvement_origine_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('commentaire', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['entree_ligne_id'], ['entree_lignes.id'], ),
    sa.ForeignKeyConstraint(['inventaire_ligne_id'], ['inventaire_lignes.id'], ),
    sa.ForeignKeyConstraint(['mouvement_origine_id'], ['mouvements_stock.id'], ),
    sa.ForeignKeyConstraint(['sortie_ligne_id'], ['sortie_lignes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vente_ligne_id'], ['vente_lignes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mouvements_stock_article_id'), ['article_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mouvements_stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mouvements_stock_article_id'))

    op.drop_table('mouvements_stock')
    op.drop_table('vente_lignes')
    op.drop_table('sortie_lignes')
    op.drop_table('inventaire_lignes')
    op.drop_table('entree_lignes')
    with op.batch_alter_table('ventes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventes_numero'))

    op.drop_table('ventes')
    with op.batch_alter_table('sorties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sorties_numero'))

    op.drop_table('sorties')
    op.drop_table('inventaires')
    with op.batch_alter_table('entrees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entrees_numero'))

    op.drop_table('entrees')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_date_heure'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_reference'))

    op.drop_table('articles')
    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    op.drop_table('parametres')
    op.drop_table('motifs_sortie')
    op.drop_table('licences')
    op.drop_table('fournisseurs')
    op.drop_table('categories')
    # ### end Alembic commands ###
